---
- name: Revoke VPN access for a user
  hosts: localhost
  pre_tasks:
    - block:
        - name: Ensure all vars defined
          assert:
            that: "{{ item }} is defined"
            msg: "variable {{ item }} must be defined"
          with_items:
            - str

  tasks:
    - set_fact:
        search_string: "search_{{ str }}"
      run_once: yes

    - name: search string
      shell: (grep {{ search_string }} /home/afif/ansible-vpn/txt/test.txt || true)
      register: presence

    - name: check if string doesn't exist
      ansible.builtin.fail:
        msg: string not found
      when: presence is not changed

    - name: Set searched string content
      copy:
        dest: "/home/afif/string.txt"
        content: "{{ search_string }}"

    - name: Changing perm sh
      file: dest=/home/afif/ansible-vpn/sh/test.sh mode=a+x

    - name: Test
      ansible.builtin.command: "/home/afif/ansible-vpn/sh/test.sh"
