---
- name: Revoke VPN access for a user
  hosts: localhost
  pre_tasks:
    - block:
        - name: Ensure all vars defined
          assert:
            that: "{{ item }} is defined"
            msg: "variable {{ item }} must be defined"
          with_items:
            - str

  tasks:
    - set_fact:
        search_string: "search_{{ str }}"
      run_once: yes

    - name: "Searching for a String"
      become: yes
      become_user: root
      tags: example1
      lineinfile:
        path: /home/afif/ansible-vpn/txt/test.txt
        line: "{{ search_string }}"
        state: present
      check_mode: yes
      register: presence
      ansible.builtin.fail:
        msg: The system may not be provisioned according to the CMDB status.
      when: presence is changed

    - name: Set searched string content
      copy:
        dest: "/home/afif/string.txt"
        content: "{{ search_string }}"

    - name: Changing perm sh
      file: dest=/home/afif/ansible-vpn/sh/test.sh mode=a+x

    - name: Test
      ansible.builtin.command: "/home/afif/ansible-vpn/sh/test.sh"
